schema = 3

[mod]
  [mod.'dario.cat/mergo']
    version = 'v1.0.2'
    hash = 'sha256-p6jdiHlLEfZES8vJnDywG4aVzIe16p0CU6iglglIweA='

  [mod.'github.com/Microsoft/go-winio']
    version = 'v0.6.2'
    hash = 'sha256-tVNWDUMILZbJvarcl/E7tpSnkn7urqgSHa2Eaka5vSU='

  [mod.'github.com/ProtonMail/go-crypto']
    version = 'v1.4.1'
    hash = 'sha256-6iGAFCjoNveY+ipbKqq2gt+RXpi2eQyPXAY01rxPcWc='

  [mod.'github.com/adrg/xdg']
    version = 'v0.5.3'
    hash = 'sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs='

  [mod.'github.com/alecthomas/chroma/v2']
    version = 'v2.20.0'
    hash = 'sha256-rL1mJS8fCltcii9w/efyyE4iyzogyjP+N80lE3CuzVE='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/aymerick/douceur']
    version = 'v0.2.0'
    hash = 'sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.2.3-0.20250311203215-f60798e515dc'
    hash = 'sha256-D9E/bMOyLXAUVOHA1/6o3i+vVmLfwIMOWib6sU7A6+Q='

  [mod.'github.com/charmbracelet/glamour']
    version = 'v1.0.0'
    hash = 'sha256-1sGgVA3QXJ2P5c/DNMb7R0HFG1X5vz9nmDhLrzKdgMw='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.1-0.20250404203927-76690c660834'
    hash = 'sha256-CwS1AyoRsPOFA4SrC0CTtwLnbg57FmmSW/mvVQUFYcc='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.10.2'
    hash = 'sha256-+JMWFbgv/5Wl2UERKxY4p5oayCRgJEDZpt2ACu3oG1o='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.13'
    hash = 'sha256-ubgBd82jcS5L4i6rCFLOB1BXGrDEu6wWlciJA0gsH2g='

  [mod.'github.com/charmbracelet/x/exp/slice']
    version = 'v0.0.0-20250327172914-2fdc97757edf'
    hash = 'sha256-C1tksnevc/RdytJRQg5LQ0+VVSWlTwbNGic649m6E1Q='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.1'
    hash = 'sha256-VBkCZLI90PhMasftGw3403IqoV7d3E5WEGAIVrN5xQM='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.7.0'
    hash = 'sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE='

  [mod.'github.com/cloudflare/circl']
    version = 'v1.6.5'
    hash = 'sha256-nrD+9cNt6xEohb0EA2bZCuSM03GXYPg/YMD0Y+HF8WU='

  [mod.'github.com/cyphar/filepath-securejoin']
    version = 'v0.7.0'
    hash = 'sha256-LMTkRIE3ZkhYDxfDt/l8EZugyoyji1u620BYzo8dd9E='

  [mod.'github.com/danielgtaylor/huma/v2']
    version = 'v2.39.1'
    hash = 'sha256-HsAT0hZKOLMrgCXyrkpaMi4UQj1whvFxSbyBCfhRPfE='

  [mod.'github.com/dlclark/regexp2']
    version = 'v1.11.5'
    hash = 'sha256-jN5+2ED+YbIoPIuyJ4Ou5pqJb2w1uNKzp5yTjKY6rEQ='

  [mod.'github.com/emirpasic/gods']
    version = 'v1.18.1'
    hash = 'sha256-hGDKddjLj+5dn2woHtXKUdd49/3xdsqnhx7VEdCu1m4='

  [mod.'github.com/fatih/color']
    version = 'v1.19.0'
    hash = 'sha256-YgMm1nid8yigNLG6aHfuMbsvMI1UYVf/Rkg44pp/NTU='

  [mod.'github.com/go-chi/chi/v5']
    version = 'v5.3.1'
    hash = 'sha256-OaGcE3d9w3Yq0ThDxG8YNvpwAQgaTsKqOL6ofZIXAB4='

  [mod.'github.com/go-git/gcfg']
    version = 'v1.5.1-0.20230307220236-3a3c6141e376'
    hash = 'sha256-f4k0gSYuo0/q3WOoTxl2eFaj7WZpdz29ih6CKc8Ude8='

  [mod.'github.com/go-git/go-billy/v5']
    version = 'v5.9.1'
    hash = 'sha256-VW8mfdLjvAuiooR2WV7P0IoOosAvtDZvFWcGQJJVSSY='

  [mod.'github.com/go-git/go-git/v5']
    version = 'v5.19.2'
    hash = 'sha256-2du2hn5JDTEEYTWuGX+heSftkmd7HoaJXyWJG4bZeSM='

  [mod.'github.com/golang/groupcache']
    version = 'v0.0.0-20241129210726-2c02b8208cf8'
    hash = 'sha256-AdLZ3dJLe/yduoNvZiXugZxNfmwJjNQyQGsIdzYzH74='

  [mod.'github.com/gorilla/css']
    version = 'v1.0.1'
    hash = 'sha256-6JwNHqlY2NpZ0pSQTyYPSpiNqjXOdFHqrUT10sv3y8A='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/jbenet/go-context']
    version = 'v0.0.0-20150711004518-d14ea06fba99'
    hash = 'sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE='

  [mod.'github.com/kevinburke/ssh_config']
    version = 'v1.6.0'
    hash = 'sha256-i/EYNJx0+HbAGFVoiKV4QF/zqb4fWewh+bpBKUkXDCc='

  [mod.'github.com/klauspost/cpuid/v2']
    version = 'v2.4.0'
    hash = 'sha256-nvTeRVxDekVNLd25aJ2NslBnG7nT25ewoSTk3iW5Xok='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

  [mod.'github.com/mattn/go-colorable']
    version = 'v0.1.15'
    hash = 'sha256-hH+yMJHjboEDQbv399OEjfc50RgtO/edw0r2sJfxEJg='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.24'
    hash = 'sha256-pmq8KKIb2+qMF3E1cR2B7NAj5joF2tZduyXjIfIlkTk='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.29'
    hash = 'sha256-AZ+wSUPj0+ZukidTuqnNogxkBKpfZ+I2LOdQ2P0ajaI='

  [mod.'github.com/microcosm-cc/bluemonday']
    version = 'v1.0.27'
    hash = 'sha256-EZSya9FLPQ83CL7N2cZy21fdS35hViTkiMK5f3op8Es='

  [mod.'github.com/muesli/reflow']
    version = 'v0.3.0'
    hash = 'sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/pjbgf/sha1cd']
    version = 'v0.6.0'
    hash = 'sha256-WC/sYIy9Iznlra87K9Gonn6/bo4a2aE+kvldecfBPfE='

  [mod.'github.com/pkg/errors']
    version = 'v0.9.1'
    hash = 'sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/sergi/go-diff']
    version = 'v1.4.0'
    hash = 'sha256-rs9NKpv/qcQEMRg7CmxGdP4HGuFdBxlpWf9LbA9wS4k='

  [mod.'github.com/skeema/knownhosts']
    version = 'v1.3.3'
    hash = 'sha256-lcQuDNZRblmXTOtE+NtNfP1Gf7BPmbqQyJLvN1Ty+dk='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/theckman/yacspin']
    version = 'v0.13.12'
    hash = 'sha256-dnYFkfKxs3P8wPnzNIKbwP1PjxnlpdNph3dyudW4fcM='

  [mod.'github.com/xanzy/ssh-agent']
    version = 'v0.3.3'
    hash = 'sha256-l3pGB6IdzcPA/HLk93sSN6NM2pKPy+bVOoacR5RC2+c='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yuin/goldmark']
    version = 'v1.7.13'
    hash = 'sha256-vBCxZrPYPc8x/nvAAv3Au59dCCyfS80Vw3/a9EXK7TE='

  [mod.'github.com/yuin/goldmark-emoji']
    version = 'v1.0.6'
    hash = 'sha256-+d6bZzOPE+JSFsZbQNZMCWE+n3jgcQnkPETVk47mxSY='

  [mod.'golang.org/x/crypto']
    version = 'v0.57.0'
    hash = 'sha256-3/hkB+mZVBKnoxUaJv7DOzvxaL+8uQ7V6ofW4JiHhz4='

  [mod.'golang.org/x/net']
    version = 'v0.59.0'
    hash = 'sha256-EGnbU9mIAvXqx4vEIWJDt+lZgs/YsUngAFJwmFSc5Tc='

  [mod.'golang.org/x/sys']
    version = 'v0.48.0'
    hash = 'sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls='

  [mod.'golang.org/x/term']
    version = 'v0.46.0'
    hash = 'sha256-w/LexmQ91G8N1zdjIujuaEIONVfAg7U/DciHVYp0+QY='

  [mod.'golang.org/x/text']
    version = 'v0.42.0'
    hash = 'sha256-bviKbNmkN4Yf2dpgwmP6yNcZEakCcv1R+YyAxCdJGkY='

  [mod.'gopkg.in/warnings.v0']
    version = 'v0.1.2'
    hash = 'sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
