name: ccli Test

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/ccli
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
